#!/usr/bin/env bun
/** make_adw — generate a new one-shot ADW script from agents in the config. */

import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { parseArgs } from "../templates/adws/adw_modules/compat/cli.ts";

const OUTPUT_TYPES: Record<string, string> = {
  planner: "PlanOutput",
  builder: "BuildOutput",
  scout: "ScoutOutput",
  reviewer: "ReviewOutput",
  documenter: "DocumentOutput",
};

const HEADER = `#!/usr/bin/env bun
/** ADW {title} — generated by make_adw.

Usage:
    bun adws/adw_{name}.ts "<prompt or path/to/prompt.md>" [--config adws/adw_sssf_config/sssf.config.yaml] [--adw-id a1b2c3d4]

Phases: engineer(request) -> {chain}
*/

import * as agents from "./adw_modules/agents.ts";
import * as gates from "./adw_modules/gates.ts";
import * as session from "./adw_modules/session.ts";
import * as utils from "./adw_modules/utils.ts";
import { parseArgs, runMain } from "./adw_modules/compat/cli.ts";
import { {imports} } from "./adw_modules/data_types.ts";

const REQUIRED_AGENTS = {agents_list};

async function main(prompt: string, config = "adws/adw_sssf_config/sssf.config.yaml", adwId: string | null = null): Promise<number> {
  const cfg = agents.loadConfig(config);
  agents.validate(cfg, REQUIRED_AGENTS);
  const run = session.ensure(cfg, adwId);

  await run.phase({ name: "request", kind: "engineer", owner: run.engineer,
    description: "Capture the incoming ask" }, async (ph) => {
    ph.log({ input: prompt });
  });

  let previous = null;
{phases}
  return run.finish();
}

const DOC = \`ADW {title} — generated by make_adw.\`;
await runMain(async () => {
  const args = parseArgs({
    description: DOC,
    positional: [{ name: "prompt", help: "inline text or a path to a prompt file" }],
    options: [
      { name: "--config", default: "adws/adw_sssf_config/sssf.config.yaml" },
      { name: "--adw-id", default: null, help: "join or pin an existing session" },
    ],
  });
  return main(utils.resolvePrompt(args.prompt!), args.config!, args.adw_id);
});
`;

const PHASE = `
  // TODO: replace this description — say what THIS phase does and why.
  previous = await run.phase({ name: "{name}", kind: "agent", owner: "{agent}",
    description: "Run {agent} over the request and hand its envelope on" }, async (ph) => {
    return ph.call({ outputType: {output_type}, prompt, previous, gates: [gates.artifactsExist] });
  });
`;

const args = parseArgs({
  description: "make_adw — generate a new one-shot ADW script from agents in the config.",
  positional: [],
  options: [
    { name: "--name", required: true, help: "snake_case adw name" },
    { name: "--agents", required: true, help: "comma-separated agent names, in order" },
    { name: "--force", dest: "force", action: "store_true" },
  ],
});

const name = args.name ?? "";
const agent_names = (args.agents ?? "").split(",").map((a) => a.trim()).filter(Boolean);
if (!agent_names.length) {
  console.log("no agents given");
  process.exit(1);
}
const types = agent_names.map((a) => OUTPUT_TYPES[a] ?? "GenericOutput");
const seen: Record<string, number> = {};
const phases: string[] = [];
for (const [i, agent] of agent_names.entries()) {
  seen[agent] = (seen[agent] ?? 0) + 1;
  const phase_name = seen[agent] === 1 ? agent : `${agent}_${seen[agent]}`;
  phases.push(PHASE.replaceAll("{name}", phase_name).replaceAll("{agent}", agent).replaceAll("{output_type}", types[i]!));
}
const body = HEADER
  .replaceAll("{title}", name.replaceAll("_", " ").replace(/\b\w/g, (c) => c.toUpperCase()))
  .replaceAll("{name}", name)
  .replaceAll("{chain}", agent_names.join(" -> "))
  .replaceAll("{imports}", [...new Set(["AgentCall", "PhaseParams", ...types])].sort().join(", "))
  .replaceAll("{agents_list}", JSON.stringify([...new Set(agent_names)].sort()).replaceAll('"', "'").replaceAll(",", ", "))
  .replaceAll("{phases}", phases.join("\n"));

const dest = join(process.cwd(), "adws", `adw_${name}.ts`);
if (existsSync(dest) && !args.force) {
  console.log(`${dest} already exists — use --force to overwrite`);
  process.exit(1);
}
mkdirSync(dirname(dest), { recursive: true });
writeFileSync(dest, body);
console.log(`wrote ${dest}`);
console.log("next: replace each phase description — a generated one says nothing, "
  + "and the description is the only intent the trace ever shows");
console.log(`run: bun adws/adw_${name}.ts "your request"`);
