#!/usr/bin/env bun
/** makeAdw — generate a new one-shot ADW script from agents in the config. */

import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { parseArgs } from "../factory/adws/adw_modules/cli.ts";

const OUTPUT_TYPES: Record<string, string> = {
  planner: "PlanOutput",
  builder: "BuildOutput",
  scout: "ScoutOutput",
  reviewer: "ReviewOutput",
  documenter: "DocumentOutput",
};

const PHASE_NAMES: Record<string, string> = {
  planner: "plan",
  builder: "build",
  scout: "scout",
  reviewer: "review",
  documenter: "document",
};

const GATES: Record<string, string[]> = {
  planner: ["gates.artifactsExist", "gates.filesNonEmpty"],
  builder: ["gates.diffMatchesClaims"],
  scout: ["gates.artifactsExist"],
  reviewer: ["gates.artifactsExist", "gates.verdictConsistent"],
  documenter: ["gates.artifactsExist", "gates.filesNonEmpty"],
};

function titleOf(name: string): string {
  return name.replaceAll("_", " ").replace(/\b\w/g, (c) => c.toUpperCase());
}

function uniqueInOrder(names: string[]): string[] {
  const out: string[] = [];
  for (const name of names) if (!out.includes(name)) out.push(name);
  return out;
}

function render(name: string, agentNames: string[]): string {
  const chain = agentNames.join(" -> ");
  const types = uniqueInOrder(agentNames.map((agent) => OUTPUT_TYPES[agent] ?? "GenericOutput")).sort();
  const required = uniqueInOrder(agentNames).map((agent) => `"${agent}"`).join(", ");
  const seen: Record<string, number> = {};
  const phases: Array<{ phaseName: string; agent: string; outputType: string }> = [];
  for (const agent of agentNames) {
    seen[agent] = (seen[agent] ?? 0) + 1;
    const base = PHASE_NAMES[agent] ?? agent;
    const phaseName = seen[agent] === 1 ? base : `${base}_${seen[agent]}`;
    phases.push({ phaseName, agent, outputType: OUTPUT_TYPES[agent] ?? "GenericOutput" });
  }
  const phaseSrc = phases.map((phase, index) => {
    const last = index === phases.length - 1;
    const previous = index === 0 ? null : phases[index - 1]!.phaseName;
    const head = last ? "await" : `const ${phase.phaseName} = await`;
    const gates = (GATES[phase.agent] ?? ["gates.artifactsExist"]).join(", ");
    const prevLine = previous ? `\n      previous: ${previous},` : "";
    return `
  // TODO: replace this description — say what THIS phase does and why.
  ${head} run.phase({
    name: "${phase.phaseName}",
    kind: "agent",
    owner: "${phase.agent}",
    description: "Run ${phase.agent} over the request and hand its envelope on",
  }, async (ph) => {
    return await ph.call({
      outputType: ${phase.outputType},
      prompt,${prevLine}
      gates: [${gates}],
    }) as ${phase.outputType};
  });`;
  }).join("\n");

  return `#!/usr/bin/env bun
const DOC = \`ADW ${titleOf(name)} — generated by makeAdw: ${chain}.

Phases: engineer(request) -> ${chain}
\`;

import * as agents from "./adw_modules/agents.ts";
import * as gates from "./adw_modules/gates.ts";
import * as session from "./adw_modules/session.ts";
import { adw } from "./adw_modules/cli.ts";
import { ${types.join(", ")} } from "./adw_modules/dataTypes.ts";

const REQUIRED_AGENTS = [${required}];

await adw(DOC, async ({ cfg, prompt, adwId }) => {
  agents.validate(cfg, REQUIRED_AGENTS);
  const run = session.ensure(cfg, adwId);
  await run.request(prompt);
${phaseSrc}

  return run.finish();
});
`;
}

const args = parseArgs({
  description: "makeAdw — generate a new one-shot ADW script from agents in the config.",
  positional: [],
  options: [
    { name: "--name", required: true, help: "snake_case adw name" },
    { name: "--agents", required: true, help: "comma-separated agent names, in order" },
    { name: "--force", dest: "force", action: "store_true" },
  ],
});

const name = args.name ?? "";
const agentNames = (args.agents ?? "").split(",").map((agent) => agent.trim()).filter(Boolean);
if (!agentNames.length) {
  console.log("no agents given");
  process.exit(1);
}
const body = render(name, agentNames);

const dest = join(process.cwd(), "adws", `adw_${name}.ts`);
if (existsSync(dest) && !args.force) {
  console.log(`${dest} already exists — use --force to overwrite`);
  process.exit(1);
}
mkdirSync(dirname(dest), { recursive: true });
writeFileSync(dest, body);
console.log(`wrote ${dest}`);
console.log("next: replace each phase description — a generated one says nothing, "
  + "and the description is the only intent the trace ever shows");
console.log(`run: bun adws/adw_${name}.ts "your request"`);
